### ISSUE TITLE
Build Issue (sdcard.h)

### ISSUE THREAD

**Issue by mnadareski** [meepingsnesroms/libretro-palmm515emu#10]
In https://github.com/meepingsnesroms/libretro-palmm515emu/commit/037cca565612ea6552a2611991d48cc8fe84e32e the name of `sdcard.h` and `sdcard.c` got changed to `sdCard.h` and `sdCard.c` respectively, but the file names were not updated accordingly. This causes issues when building on linux.

**Comment by meepingsnesroms** [comment]
Git dident detect the filename changes since Mac isnt case sensitive, I removed and reuploaded the files, reclone the project and try again it should work now.

**Comment by mnadareski** [comment]
Looks good! Thank you again (and yeah, things like Windows do the same thing, it's rather annoying sometimes...)
