### ISSUE TITLE
Non-commercial license

### ISSUE THREAD

**Issue by gameblabla** [meepingsnesroms/libretro-palmm515emu#2]
Hello guicrith,
i remember when you were working on PersianTree before it eventually became this, pretty nice progress so far ! However, one thing i did not notice was the license...
I won't go around the bushes, it's a major turn off for me. Such a license would also prevent it from being bundled with linux distributions.

I don't know your exact motives but just in case you did it in case someone else would take your work and profit off of it : 
It's likely that such license is going to be ineffective at it. 
The non-commercial license for Snes9x was ignored by most "emulation boxes" and you'll always have scums like DamonPS2 violating GPL anyway. (even though they could still make money off of it, but they don't want to share the source, violating the license still)
It's the reason why MAME dropped their old license, as it was never enforced and indeed some deemed it to be unenforceable. The moment they changed the license, they finally started to get credits for their work.

The only thing it will do is to punish legitimate users, which is why i would like you to reconsider the license. I would probably recommend the GPLv3+, since it requires modifications to be made public, along with other restrictions.

**Comment by meepingsnesroms** [comment]
There are no bundling restrictions, the only restrictions are you cant sell it and you cant claim its your own, why would those 2 prevent it from being bundled?
I chose this license because it should be compatible with everything and understand that if you are just doing a school project or using it for a very specialized use(extra hardware registers to control your partys disco ball?) having to maintain a source repo forever to prevent a license violation is a unnecessary burden.

Also a major turn off for what, using it to play Palm games or development?

**Comment by gameblabla** [comment]
Hello,
thank you for your answer. Perhaps i should clarify a few points.

> There are no bundling restrictions, the only restrictions are you cant sell it and you cant claim its your own, why would those 2 prevent it from being bundled?

Some linux distributions (which includes Debian) have a policy of not including so-called "non-free" software as part of the base repo. For example for years, it was not possible to do "apt-get install mame" because of this policy, until 2016 when they changed the license. This license is not free software because it prevents commercial usage. 

> understand that if you are just doing a school project or using it for a very specialized use(extra hardware registers to control your partys disco ball?) having to maintain a source repo forever to prevent a license violation is a unnecessary burden.

I fail to understand this how the CC NC is going to prevent the "unnecessary burden" ? And is it not actually a good thing that you get to have their own modifications to your very own code ? I would personally hate if a substantial project like yours would get forked, only to then be refused to the source code and its modifications.  

> Also a major turn off for what, using it to play Palm games or development?

Mostly for development and personal reasons. Let's say that i had my own share of bad experiences with proprietary software... Of course, if i only cared about playing Palm games and nothing else, then i probably wouldn't care for the license but after seeing the incident Genesis Plus GX & Snes9X generated with their own license with Hyperkin that became quite ugly (i'll spare you of the details), maybe it's best to switch licenses for that reason alone. 

Understand that even using small parts of your code in other projects, even ones unrelated to yours, would introduce a non-free dependency on the whole program. It goes a bit farther than one could think.

You could choose to stick with this license while you continue working and not give a thought to it anymore, but i just want to say that even the PalmOS commnuity had benefited from software being GPL-licensed. Wouldn't you hate if GCC had added a clause saying that compiled programs cannot be used for profit ?

As i understand, it's not like you intend to sell commercial licenses for this project in the future anyway ?
I hope this has not scared you and if you need more details, i'll be happy to talk about it.

**Comment by meepingsnesroms** [comment]
> Wouldn't you hate if GCC had added a clause saying that compiled programs cannot be used for profit ?
I would actually like that alot.

From my view whenever money is involved it destroys everything it touches, so anything that can prevent the further monitisation of emulation and software I am all for.
(social media tracking, pay to win in video games, all the various squabbles in the switch hacking scene, inferior medical care)

> Some linux distributions (which includes Debian) have a policy of not including so-called "non-free" software as part of the base repo.
Thats their problem, I dont intend to cater to extremist views.

>  Of course, if i only cared about playing Palm games and nothing else, then i probably wouldn't care for the license but after seeing the incident Genesis Plus GX & Snes9X generated with their own license with Hyperkin that became quite ugly (i'll spare you of the details), maybe it's best to switch licenses for that reason alone.
This is just retarded, thats like saying it wouldn't have been rape if you just would've said yes.
This is a persistent issue with tech companys and regulations, they do what ever the hell they want and then say "oops" when they get caught, its not Snes9Xs fault.

I may change it to a GPL equivalent with a non commercial restriction though so forks have to share their changes.

**Comment by gameblabla** [comment]
Alright then, i feel like this is going nowhere then and i do not like being called a retard.
I will close this issue and pretend nothing happened.
