### ISSUE TITLE
Nit: .gitignore .pro.user

### ISSUE THREAD

**Issue by mnadareski** [meepingsnesroms/libretro-palmm515emu#7]
This is about as nitpicky as they come, so I apologize in advance. I've had issues loading the `.pro` file locally if I try to use the checked in `.pro.user` settings file. I have to wipe it out each time in order for things to run. It might be worthwhile to add the user settings to `.gitignore`. This will also make some of the commits less packed.

**Comment by meepingsnesroms** [comment]
Thats not nitpicky, it should load properly without needing any file deleted.
Try now, all .pro.user files where removed

**Comment by mnadareski** [comment]
All good again, thanks!
