### ISSUE TITLE
When compiled some builds wont send any touch input

### ISSUE THREAD

**Issue by meepingsnesroms** [meepingsnesroms/libretro-palmm515emu#8]
The cause is unknown but was associated with building outside Qt Creator.
The used ROM may also play a role.

[Previous Disscussion](https://github.com/meepingsnesroms/libretro-palmm515emu/issues/6)

**Comment by mnadareski** [comment]
I can confirm (finally) that an externally built version will run but will not respond to touch inputs.

Building with the same version of 5.11.1 that Qt Creator was using.

**Comment by meepingsnesroms** [comment]
I think I know, since this emulator is supossed to be accurate it has to be compiled in debug mode for the touch hack to be active and when not active no events are sent, try compiling in debug mode.

**Comment by parkerlreed** [comment]
Yep that's it. 

````
qmake CONFIG+=debug 
make -j4
````

And it shows the touch data and works.

**Comment by mnadareski** [comment]
If you can update the build instructions with this info, that would be great 👍
