### ISSUE TITLE
Add runtime instructions to README

### ISSUE THREAD

**Issue by mnadareski** [meepingsnesroms/libretro-palmm515emu#9]
In one of the recent updates, it seems like the bootloader was added as a requirement for running the program. It might be useful to add those setup instructions (add files to whatever folder) to the main README.

Also, since the other issue about qmake was closed, it might also be helpful to update the "build without Qt Creator" instructions to use `qmake CONFIG+=debug` instead of just `qmake`.

**Comment by meepingsnesroms** [comment]
I just added full setup directions in the last commit.
For the debug thing though, I dont want to spread the touchscreen hack any further, it will be fixed once I get apps loading and would be best if it doesnt have to be painfully extracted from every file after.

**Comment by mnadareski** [comment]
Sounds and looks good. Thanks!
