### ISSUE TITLE
Where can I download these rom files?

### ISSUE THREAD

**Issue by potatomatos** [meepingsnesroms/libretro-palmm515emu#98]
Where can I download these files:
palmos40-en-m500.rom: f50e4d5e4d98dc831f2c34a9107651eb (MD5)
palmos41-en-m515.rom: 83cb1d1c76e568b916dc2e7c0bf669f6 (MD5)
palmos52-en-t3.rom: de46ec84d9aabf655eabdf9b00a3845d (MD5)
bootloader-dbvz.rom: 9da101cd2317830649a31f8fa46debec (MD5)

Don't know GitHub very well

**Comment by parkerlreed** [comment]
The m515 is here https://palmdb.net/mu-emulator/

The PalmOS 52 is only for internal testing and doesn't current boot completely.

**Comment by potatomatos** [comment]
> The m515 is here https://palmdb.net/mu-emulator/
> 
> The PalmOS 52 is only for internal testing and doesn't current boot completely.

i see,thank you very much,but It is very difficult to find the OS5.2 rom on the Internet. I have searched for two days and have not found it

**Comment by parkerlreed** [comment]
@potatomatos Yes my point is it is not widely available because it is just for internal testing at the moment.

**Comment by parkerlreed** [comment]
The community does have a copy. I currently do not have it.
